# Generated by Django 3.0.6 on 2020-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='secretkey',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
    ]
